### ISSUE TITLE
Starting moonshine

### ISSUE THREAD

**Issue by kathaurielle** [exponential-decay/moonshine#5]
Hello, would it be possible to have some guidance on using moonshine please? Have downloaded it, how do we proceed from then? Best wishes, Kathryn

**Comment by ross-spencer** [comment]
Hi Kathryn - you need to run the tool on the command line, for example, the easiest way is just to be in the same folder as the binary, and then you can run it using the instructions in the README: https://github.com/exponential-decay/moonshine#moonshine -- on Windows, you don't need `./`.

**Comment by kathaurielle** [comment]
Ahh thanks Ross, will give it a go.
